# nuget token expires Aug 2022
name: Build and Test and Publish (release)

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Build and test
      run: dotnet fake build -t Release
    - name: Deploy documentation from master
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
    - name: Examine bin
      run: ls -r bin
    - name: Publish NuGets (if this version not published before)
      run: dotnet nuget push bin\FSharp.Data.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGETKEY }} --skip-duplicate

